name: Develop Branch Workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: |
        dotnet new sln
        cd ./Core/Runtime
        dotnet new classlib
        dotnet add package Unity3D.UnityEngine --version 2018.3.5.1
        cd ../..
        dotnet sln add ./Core/Runtime/Runtime.csproj
        dotnet restore
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd ./Core/Tests
        dotnet new nunit
        dotnet add package NSubstitute --version 4.2.2
        dotnet add package NUnit3TestAdapter --version 3.17.0
        cd ../..
        dotnet sln add ./Core/Tests/Tests.csproj
        dotnet add ./Core/Tests/Tests.csproj reference ./Core/Runtime/Runtime.csproj
        dotnet restore
    - uses: dodopizza/dotcover-action@v1
      with:
        dotCoverCommand: dotnet --ReportType=NDependXML --Output="./Coverage/Core_coverage.xml" -- test "./Core/Tests/Tests.csproj"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Core Coverage
        path: ./Coverage/Core_coverage.xml
    - name: Upload Coverage Report
      uses: codecov/codecov-action@v1.0.12 
