name: Develop Branch Workflow

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build Code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: |
        dotnet new sln
        cd ./Core/Runtime
        dotnet new classlib
        dotnet add package Unity3D.UnityEngine --version 2018.3.5.1
        cd ../..
        dotnet sln add ./Core/Runtime/Runtime.csproj
        dotnet restore
        dotnet build --configuration Release --no-restore
    - name: Cache Coverage Tools
      id: cacheDotCover
      uses: actions/cache@v2
      with:
        path: |
          dotCover
        key: ${{ runner.os }}-DotCover
    - name: Install Coverage Tools
      if: steps.cacheDotCover.outputs.cache-hit != 'true'
      run: |
        mkdir dotCover
        cd dotCover
        curl https://download.jetbrains.com/resharper/ReSharperUltimate.2020.1.4/JetBrains.dotCover.CommandLineTools.linux-x64.2020.1.4.tar.gz -o ./JetBrains.dotCover.CommandLineTools.linux-x64.2020.1.4.tar.gz 
        tar xvf ./JetBrains.dotCover.CommandLineTools.linux-x64.2020.1.4.tar.gz
    - name: Test
      run: |
        cd ./Core/Tests
        dotnet new nunit
        dotnet add package NSubstitute --version 4.2.2
        dotnet add package NUnit3TestAdapter --version 3.17.0
        cd ../..
        dotnet sln add ./Core/Tests/Tests.csproj
        dotnet add ./Core/Tests/Tests.csproj reference ./Core/Runtime/Runtime.csproj
        dotnet restore
        dotnet test -r ../../test_results/core/ --logger "trx"  
        ./dotCover/dotCover.exe dotnet --output=Core_Coverage.xml --reportType=XML -- test
    - name: Upload Coverage Report
      uses: codecov/codecov-action@v1.0.12 
